In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Storing Names of Sin and Non-Sin Stocks in Variables

In [2]:
non_sin_df = pd.read_excel("Monthly Return_Coffee Products.xlsx", parse_dates = True)
sin_df = pd.read_excel("Monthly Return_Alcoholic Products.xlsx", parse_dates = True)

In [3]:
sin_df.head()

,PERMNO,Names Date,Standard Industrial Classification Code,Ticker Symbol,Company Name,Price or Bid/Ask Average
0,10225,2011-10-31,2082,BEAM,BEAM INC,49.430000
1,10225,2011-11-30,2082,BEAM,BEAM INC,52.520000
2,10225,2011-12-30,2082,BEAM,BEAM INC,51.230000
3,10225,2012-01-31,2082,BEAM,BEAM INC,52.310001
4,10225,2012-02-29,2082,BEAM,BEAM INC,55.080002

In [4]:
sin_list = sin_df["Ticker Symbol"].unique()
sin_list

array(['BEAM', 'BEER', 'PFB', 'ABW', 'GBL', 'RUP', 'CNB', 'CKB', 'FAL',
       'FALB', 'DRE', 'NBW', 'GENBB', 'RG', 'RGLD', 'SLZ', 'SFR', 'KNBWY',
       'GRRR', nan, 'LONE', 'GHB', 'ABUD', 'BUD', 'ACCOB', 'RKY', 'TAP',
       'PABT', 'OLYB', 'PTBC', 'HAN', 'BAS', 'SXC', 'CU', 'CCU', 'THT',
       'HOOK', 'BREW', 'SAM', 'CFN', 'IBCO', 'BRH', 'ABV', 'ABEV', 'AED',
       'MLB', 'LQU', 'ROX', 'CREG', 'BORN', 'FO', 'MWGP', 'MGPI', 'AFTI',
       'DR', 'CUE', 'BACA', 'BBRL', 'ADC', 'SH', 'DCS', 'VO', 'HIR',
       'CHLN', 'CGAS', 'BJD', 'BFD', 'BF', 'CDL', 'DIL', 'GDS', 'SBR',
       'HBL', 'TFZ', 'TFI', 'HTC', 'JACQ', 'BBR', 'CNWN', 'CDG', 'CDB',
       'STZ', 'RAIN', 'TBVT', 'TYLR', 'THTR', 'DEO', 'RUM', 'VCO', 'ADSO',
       'NDC', 'GWT', 'CEDC', 'PTT'], dtype=object)

In [5]:
non_sin_list = non_sin_df["Ticker Symbol"].unique()
non_sin_list

array(['FARM', 'GMCR', 'PEET', 'JVA'], dtype=object)

# Reading in Files

In [6]:
stocks_df = pd.read_csv("final_merged.csv", parse_dates = ["Unnamed: 0"])
stocks_df.set_index("Unnamed: 0", inplace=True)
stocks_df.index.name = "Date"
stocks_df.head()

,ABEV,ABUD,ABV,ABW,ACCOB,ADC,ADSO,AED,AFTI,BACA,...,VO,FARM,GMCR,JVA,PEET,Excess Return on the Market,SMB,HML,MOM,USREC
Date,,,,,,,,,,,,,,,,,,,,,
1962-07-31,NaN,NaN,NaN,NaN,NaN,37.000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0628,0.0163,-0.0357,0.0055,0
1962-08-31,NaN,NaN,NaN,NaN,NaN,37.250,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0213,0.0125,-0.0121,-0.0058,0
1962-09-30,NaN,NaN,NaN,NaN,NaN,37.250,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,-0.0522,-0.0248,0.0134,0.0395,0
1962-10-31,NaN,NaN,NaN,NaN,NaN,33.375,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,-0.0005,-0.0401,0.0135,0.0075,0
1962-11-30,NaN,NaN,NaN,2.5,NaN,39.625,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.1087,0.0259,0.0099,-0.0717,0

# Further Data Cleaning

## Isolating Sin Stocks Only

In [7]:
# Removing the NaN value in sin_list
sin_list = sin_list[~pd.isnull(sin_list)]
sin_list

array(['BEAM', 'BEER', 'PFB', 'ABW', 'GBL', 'RUP', 'CNB', 'CKB', 'FAL',
       'FALB', 'DRE', 'NBW', 'GENBB', 'RG', 'RGLD', 'SLZ', 'SFR', 'KNBWY',
       'GRRR', 'LONE', 'GHB', 'ABUD', 'BUD', 'ACCOB', 'RKY', 'TAP',
       'PABT', 'OLYB', 'PTBC', 'HAN', 'BAS', 'SXC', 'CU', 'CCU', 'THT',
       'HOOK', 'BREW', 'SAM', 'CFN', 'IBCO', 'BRH', 'ABV', 'ABEV', 'AED',
       'MLB', 'LQU', 'ROX', 'CREG', 'BORN', 'FO', 'MWGP', 'MGPI', 'AFTI',
       'DR', 'CUE', 'BACA', 'BBRL', 'ADC', 'SH', 'DCS', 'VO', 'HIR',
       'CHLN', 'CGAS', 'BJD', 'BFD', 'BF', 'CDL', 'DIL', 'GDS', 'SBR',
       'HBL', 'TFZ', 'TFI', 'HTC', 'JACQ', 'BBR', 'CNWN', 'CDG', 'CDB',
       'STZ', 'RAIN', 'TBVT', 'TYLR', 'THTR', 'DEO', 'RUM', 'VCO', 'ADSO',
       'NDC', 'GWT', 'CEDC', 'PTT'], dtype=object)

In [8]:
sin_stocks = stocks_df[sin_list]
sin_stocks.head()

,BEAM,BEER,PFB,ABW,GBL,RUP,CNB,CKB,FAL,FALB,...,TYLR,THTR,DEO,RUM,VCO,ADSO,NDC,GWT,CEDC,PTT
Date,,,,,,,,,,,,,,,,,,,,,
1962-07-31,NaN,NaN,2.625,NaN,1.250,13.2500,8.500,NaN,32.500,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1962-08-31,NaN,NaN,2.875,NaN,1.375,13.3125,9.000,NaN,32.250,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1962-09-30,NaN,NaN,2.750,NaN,1.125,12.6875,8.500,NaN,30.000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1962-10-31,NaN,NaN,2.375,NaN,0.625,11.6875,9.000,NaN,28.750,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1962-11-30,NaN,NaN,NaN,2.5,NaN,11.9375,9.625,NaN,31.125,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Finding Percentage Change in Stocks

In [9]:
returns_df = sin_stocks.pct_change(limit = 1)
returns_df

,BEAM,BEER,PFB,ABW,GBL,RUP,CNB,CKB,FAL,FALB,...,TYLR,THTR,DEO,RUM,VCO,ADSO,NDC,GWT,CEDC,PTT
Date,,,,,,,,,,,,,,,,,,,,,
1962-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1962-08-31,NaN,NaN,0.095238,NaN,0.100000,0.004717,0.058824,NaN,-0.007692,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1962-09-30,NaN,NaN,-0.043478,NaN,-0.181818,-0.046948,-0.055556,NaN,-0.069767,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1962-10-31,NaN,NaN,-0.136364,NaN,-0.444444,-0.078818,0.058824,NaN,-0.041667,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1962-11-30,NaN,NaN,0.000000,NaN,0.000000,0.021390,0.069444,NaN,0.082609,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-0.087205,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.024256,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-0.054337,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.190275,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.024911,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
returns_df_test = sin_stocks.pct_change(limit = None, fill_method = None)
returns_df_test

,BEAM,BEER,PFB,ABW,GBL,RUP,CNB,CKB,FAL,FALB,...,TYLR,THTR,DEO,RUM,VCO,ADSO,NDC,GWT,CEDC,PTT
Date,,,,,,,,,,,,,,,,,,,,,
1962-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1962-08-31,NaN,NaN,0.095238,NaN,0.100000,0.004717,0.058824,NaN,-0.007692,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1962-09-30,NaN,NaN,-0.043478,NaN,-0.181818,-0.046948,-0.055556,NaN,-0.069767,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1962-10-31,NaN,NaN,-0.136364,NaN,-0.444444,-0.078818,0.058824,NaN,-0.041667,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1962-11-30,NaN,NaN,NaN,NaN,NaN,0.021390,0.069444,NaN,0.082609,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-0.087205,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.024256,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-0.054337,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.190275,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.024911,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Removing null values
- Only the first row is empty, since we found percentage changes for each adjacent row

In [106]:
returns_df.dropna(how = "all", inplace=True)
returns_df

,BEAM,BEER,PFB,ABW,GBL,RUP,CNB,CKB,FAL,FALB,...,TYLR,THTR,DEO,RUM,VCO,ADSO,NDC,GWT,CEDC,PTT
Date,,,,,,,,,,,,,,,,,,,,,
1962-08-31,NaN,NaN,0.095238,NaN,0.100000,0.004717,0.058824,NaN,-0.007692,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1962-09-30,NaN,NaN,-0.043478,NaN,-0.181818,-0.046948,-0.055556,NaN,-0.069767,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1962-10-31,NaN,NaN,-0.136364,NaN,-0.444444,-0.078818,0.058824,NaN,-0.041667,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1962-11-30,NaN,NaN,0.000000,NaN,0.000000,0.021390,0.069444,NaN,0.082609,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1962-12-31,NaN,NaN,NaN,0.0,NaN,0.015707,0.038961,NaN,-0.028112,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-0.087205,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.024256,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-0.054337,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.190275,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.024911,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Calculating Individual Weights

In [107]:
total_no_sin = len(returns_df.columns)
total_no_sin

93

### Calculating Number of Active Stocks for Each Date
- Deducting number of NaN values per row from the total number of sin stocks to derive the number of active sin stocks for a given date

In [108]:
returns_df["Num_Active_Stocks"] = total_no_sin - returns_df.isnull().sum(axis = 1)
returns_df["Portfolio_Proportion"] = 1 / returns_df["Num_Active_Stocks"]
returns_df

,BEAM,BEER,PFB,ABW,GBL,RUP,CNB,CKB,FAL,FALB,...,DEO,RUM,VCO,ADSO,NDC,GWT,CEDC,PTT,Num_Active_Stocks,Portfolio_Proportion
Date,,,,,,,,,,,,,,,,,,,,,
1962-08-31,NaN,NaN,0.095238,NaN,0.100000,0.004717,0.058824,NaN,-0.007692,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19,0.052632
1962-09-30,NaN,NaN,-0.043478,NaN,-0.181818,-0.046948,-0.055556,NaN,-0.069767,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19,0.052632
1962-10-31,NaN,NaN,-0.136364,NaN,-0.444444,-0.078818,0.058824,NaN,-0.041667,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19,0.052632
1962-11-30,NaN,NaN,0.000000,NaN,0.000000,0.021390,0.069444,NaN,0.082609,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19,0.052632
1962-12-31,NaN,NaN,NaN,0.0,NaN,0.015707,0.038961,NaN,-0.028112,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18,0.055556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.087205,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,0.090909
2020-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.024256,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,0.090909
2020-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.054337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,0.100000
2020-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.190275,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,0.100000
2020-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.024911,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,0.100000

## Multiplying percentage returns by 1/N stocks (Portfolio_Proportion)

In [110]:
portfolio_returns = returns_df.mul(returns_df["Portfolio_Proportion"], axis = 0)
portfolio_returns.drop(columns = ["Num_Active_Stocks", "Portfolio_Proportion"], inplace = True)

## Finding Row Wise Sum of Portfolio Percentage Returns

In [111]:
portfolio_returns["Portfolio_Returns"] = portfolio_returns.sum(axis = 1)

In [112]:
portfolio_returns["Portfolio_Proportion"] = returns_df["Portfolio_Proportion"]
portfolio_returns

,BEAM,BEER,PFB,ABW,GBL,RUP,CNB,CKB,FAL,FALB,...,RUM,VCO,ADSO,NDC,GWT,CEDC,PTT,test,Portfolio_Returns,Portfolio_Proportion
Date,,,,,,,,,,,,,,,,,,,,,
1962-08-31,NaN,NaN,0.005013,NaN,0.005263,0.000248,0.003096,NaN,-0.000405,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.028063,0.052632
1962-09-30,NaN,NaN,-0.002288,NaN,-0.009569,-0.002471,-0.002924,NaN,-0.003672,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.390793,0.052632
1962-10-31,NaN,NaN,-0.007177,NaN,-0.023392,-0.004148,0.003096,NaN,-0.002193,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.095336,0.052632
1962-11-30,NaN,NaN,0.000000,NaN,0.000000,0.001126,0.003655,NaN,0.004348,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.039588,0.052632
1962-12-31,NaN,NaN,NaN,0.0,NaN,0.000873,0.002165,NaN,-0.001562,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.401140,0.055556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.132603,0.090909
2020-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.481357,0.090909
2020-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.116476,0.100000
2020-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.277553,0.100000
2020-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134.027247,0.100000

In [115]:
portfolio_returns.to_csv("sin_portfolio_returns.csv")